apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: test-lab
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy: {}
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress:php8.4
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql.test-lab.svc.cluster.local"
            - name: WORDPRESS_DB_USER
              value: "root"
            - name: WORDPRESS_DB_NAME
              value: "wordpress"
            - name: WORDPRESS_DB_PASSWORD
              value: "somewordpress"
          ports:
            - containerPort: 80
          resources: {}
