apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: test-lab
  labels:
    app: wordpress
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - name: wordpress
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30000
