apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: test-lab
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
