configs:
  registry.test.local:
    tls:
      insecure_skip_verify: true

  # registry.test.local:
  #   # auth:
  #   #   username: <BASIC AUTH USERNAME>
  #   #   password: <BASIC AUTH PASSWORD>
  #   #   token: <BEARER TOKEN>
  #   tls:
  #     ca_file: <PATH TO SERVER CA>
  #     cert_file: <PATH TO CLIENT CERT>
  #     key_file: <PATH TO CLIENT KEY>
  #     insecure_skip_verify: <SKIP TLS CERT VERIFICATION BOOLEAN>
