apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-longhorn
  namespace: test-lab
spec:
  resources:
    requests:
      storage: "1Gi"
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  storageClassName: "longhorn"
