apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: test-lab
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy: {}
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress:php8.4
          name: wordpress
          env:
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: WORDPRESS_DB_PASSWORD
                  name: wordpress-db-secret
          envFrom:
            - configMapRef:
                name: wordpress-config
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
